XuanKyUEL/MCommerce_UniPet_Project

app/src/main/java/com/unipet7/mcommerce/activities/MainActivity.java
app/src/main/java/com/unipet7/mcommerce/activities/SignIn.java
app/src/main/java/com/unipet7/mcommerce/activities/SignUp.java
app/src/main/res/drawable/clear_input.xml
app/src/main/res/drawable/ic_back_signup.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/layout/fragment_blank_cart.xml

UI: signUp back icon to signIn screen

UI: signUp back icon to signIn screen

---

app/src/main/java/com/unipet7/mcommerce/activities/MainActivity.java
app/src/main/res/layout/activity_main.xml

UI: Fix bottom nav too high

---

app/src/main/java/com/unipet7/mcommerce/activities/MainActivity.java
app/src/main/java/com/unipet7/mcommerce/activities/SplashScreen.java
app/src/main/java/com/unipet7/mcommerce/adapters/MainViewPager2Adapter.java
app/src/main/java/com/unipet7/mcommerce/firebase/FireStoreClass.java
app/src/main/java/com/unipet7/mcommerce/fragments/FragmentBlog.java
app/src/main/java/com/unipet7/mcommerce/fragments/Home.java
app/src/main/java/com/unipet7/mcommerce/fragments/Profile.java
app/src/main/java/com/unipet7/mcommerce/utils/LoadingDialog.java
app/src/main/res/layout/activity_main.xml

Refactor: fragment container to viewpager2 in MainActivity

---

app/src/main/java/com/unipet7/mcommerce/fragments/FragmentRateOrder.java
app/src/main/java/com/unipet7/mcommerce/fragments/Home.java
app/src/main/res/layout/fragment_rate_order.xml

Rateorder Frag

---

app/src/main/java/com/unipet7/mcommerce/activities/RateOrder.java
app/src/main/java/com/unipet7/mcommerce/fragments/Home.java
app/src/main/res/layout/activity_rate_order.xml

Reverts XuanKyUEL/MCommerce_UniPet_Project#44

Revert "Rateorder Frag"

---

app/src/main/java/com/unipet7/mcommerce/activities/MainActivity.java
app/src/main/java/com/unipet7/mcommerce/activities/VoucherActivity.java
app/src/main/java/com/unipet7/mcommerce/adapters/AdapterVoucher.java
app/src/main/java/com/unipet7/mcommerce/adapters/CartAdapter.java
app/src/main/java/com/unipet7/mcommerce/adapters/MainViewPager2Adapter.java
app/src/main/java/com/unipet7/mcommerce/adapters/NotiAdapter.java
app/src/main/java/com/unipet7/mcommerce/fragments/fragment_cart.java
app/src/main/java/com/unipet7/mcommerce/models/ProductCart.java
app/src/main/java/com/unipet7/mcommerce/models/Voucher.java
app/src/main/res/layout/activity_voucher.xml
app/src/main/res/layout/cart_item_recycleview.xml
app/src/main/res/layout/fragment_cart.xml
app/src/main/res/layout/notification_item_layout.xml
app/src/main/res/layout/voucher_item.xml

Thêm chức năng cart, xem lại lỗi UI voucher

Add cart function, however voucher still error

---

.idea/deploymentTargetDropDown.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/unipet7/mcommerce/adapters/BlogAdapter.java
app/src/main/java/com/unipet7/mcommerce/firebase/FireStoreClass.java
app/src/main/java/com/unipet7/mcommerce/fragments/FragmentAllProduct.java
app/src/main/java/com/unipet7/mcommerce/fragments/FragmentBlogDetails.java
app/src/main/java/com/unipet7/mcommerce/fragments/Home.java
app/src/main/java/com/unipet7/mcommerce/fragments/Profile.java
app/src/main/java/com/unipet7/mcommerce/fragments/fragment_notification.java
app/src/main/res/layout/fragment_all_product.xml
app/src/main/res/layout/fragment_blog.xml
app/src/main/res/layout/fragment_blog_details.xml
app/src/main/res/layout/fragment_contact_list.xml
app/src/main/res/layout/fragment_notification.xml
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/layout/item_layout.xml
app/src/main/res/layout/layout_questions_support.xml
app/src/main/res/layout/notification_item_layout.xml

fix item layout and blog

---

app/src/main/java/com/unipet7/mcommerce/activities/DetailProduct.java
app/src/main/java/com/unipet7/mcommerce/activities/SignUp.java
app/src/main/java/com/unipet7/mcommerce/fragments/FragmentAccount.java
app/src/main/java/com/unipet7/mcommerce/fragments/Profile.java
app/src/main/res/layout/activity__detail__product.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/layout/fragment_profile.xml

Func: Load Product Details Img and phone of User

Func: Load Product Details Img and phone of User

---

app/src/main/java/com/unipet7/mcommerce/activities/BlogDetails.java
app/src/main/java/com/unipet7/mcommerce/activities/Blogs.java
app/src/main/java/com/unipet7/mcommerce/activities/DetailProduct.java
app/src/main/java/com/unipet7/mcommerce/adapters/FavProductInterface.java
app/src/main/java/com/unipet7/mcommerce/adapters/ProductAdapter.java
app/src/main/java/com/unipet7/mcommerce/firebase/FireStoreClass.java
app/src/main/java/com/unipet7/mcommerce/fragments/Fragment_Wishlist_Product.java
app/src/main/java/com/unipet7/mcommerce/fragments/Home.java
app/src/main/res/layout/activity__detail__product.xml
app/src/main/res/layout/activity_blog_details.xml
app/src/main/res/layout/fragment__wishlist__product.xml
app/src/main/res/layout/fragment_all_product.xml
app/src/main/res/layout/item_layout.xml

Func: Add/Remove from wish_list, heart still error

Func: Add/Remove from wish_list, heart still error

---

app/src/main/java/com/unipet7/mcommerce/activities/BlogDetails.java
app/src/main/java/com/unipet7/mcommerce/activities/SearchProductList.java
app/src/main/java/com/unipet7/mcommerce/adapters/ProductAdapter.java
app/src/main/java/com/unipet7/mcommerce/firebase/FireStoreClass.java
app/src/main/java/com/unipet7/mcommerce/fragments/FragmentAllProduct.java
app/src/main/java/com/unipet7/mcommerce/fragments/Fragment_Wishlist_Product.java
app/src/main/java/com/unipet7/mcommerce/fragments/Home.java
app/src/main/java/com/unipet7/mcommerce/models/Product.java

Oncompleting wishlist

---

app/src/main/java/com/unipet7/mcommerce/activities/Blogs.java
app/src/main/java/com/unipet7/mcommerce/activities/SearchProductList.java
app/src/main/java/com/unipet7/mcommerce/firebase/FireStoreClass.java
app/src/main/java/com/unipet7/mcommerce/fragments/ContactList.java
app/src/main/java/com/unipet7/mcommerce/fragments/FragmentHistoryOrders.java
app/src/main/java/com/unipet7/mcommerce/fragments/Home.java
app/src/main/java/com/unipet7/mcommerce/fragments/Question.java
app/src/main/res/drawable/input_field.xml
app/src/main/res/layout/activity__detail__product.xml
app/src/main/res/layout/activity_blog_details.xml
app/src/main/res/layout/activity_blogs.xml
app/src/main/res/layout/activity_notification.xml
app/src/main/res/layout/activity_search_product_list.xml
app/src/main/res/layout/fragment__wishlist__product.xml
app/src/main/res/layout/fragment_address.xml
app/src/main/res/layout/fragment_all_product.xml
app/src/main/res/layout/fragment_help_center.xml
app/src/main/res/layout/fragment_history_orders.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/fragment_payment_method.xml
app/src/main/res/layout/fragment_question.xml

Search product filter + change UI history order button

Search product filter + change UI history order button

---

app/src/main/java/com/unipet7/mcommerce/activities/Blogs.java
app/src/main/java/com/unipet7/mcommerce/adapters/CartAdapter.java
app/src/main/java/com/unipet7/mcommerce/fragments/fragment_cart.java
app/src/main/java/com/unipet7/mcommerce/models/Product.java
app/src/main/res/layout/fragment_cart.xml

Change UI price in cart

---

app/src/main/java/com/unipet7/mcommerce/adapters/ProductAdapter.java
app/src/main/java/com/unipet7/mcommerce/firebase/FireStoreClass.java
app/src/main/java/com/unipet7/mcommerce/models/Product.java

Wisht list fix hear icon (still error in Home)

Wisht list fix hear icon (still error in Home)

---

app/src/main/java/com/unipet7/mcommerce/activities/SearchProductList.java
app/src/main/java/com/unipet7/mcommerce/adapters/CartAdapter.java
app/src/main/java/com/unipet7/mcommerce/adapters/ProductAdapter.java
app/src/main/java/com/unipet7/mcommerce/fragments/FragmentAllProduct.java
app/src/main/res/layout/activity_blog_details.xml
app/src/main/res/layout/fragment_all_product.xml

Search Keyword at search product list and search keyword at all product

Search Keyword at search product list and search keyword at all product

---

app/src/main/java/com/unipet7/mcommerce/activities/DetailProduct.java
app/src/main/java/com/unipet7/mcommerce/activities/VoucherActivity.java
app/src/main/java/com/unipet7/mcommerce/adapters/MessageDialogAdapter.java
app/src/main/java/com/unipet7/mcommerce/adapters/ProductAdapter.java
app/src/main/java/com/unipet7/mcommerce/firebase/FireStoreClass.java
app/src/main/java/com/unipet7/mcommerce/fragments/FragmentAllProduct.java
app/src/main/java/com/unipet7/mcommerce/fragments/fragment_cart.java
app/src/main/res/layout/activity__detail__product.xml
app/src/main/res/layout/dialogmessage.xml

Chức năng thêm vào giỏ hàng từ  productdetail

Duong luan

---

app/src/main/java/com/unipet7/mcommerce/activities/BlogDetails.java
app/src/main/java/com/unipet7/mcommerce/firebase/FireStoreClass.java

Fix: Get random 10 products to blog details

Fix: Get random 10 products to blog details

---

app/src/main/java/com/unipet7/mcommerce/activities/DetailProduct.java
app/src/main/java/com/unipet7/mcommerce/adapters/AddressAdapter.java
app/src/main/java/com/unipet7/mcommerce/firebase/FireStoreClass.java
app/src/main/java/com/unipet7/mcommerce/fragments/FragmentAddress.java
app/src/main/java/com/unipet7/mcommerce/fragments/FragmentAddressEdit.java
app/src/main/java/com/unipet7/mcommerce/fragments/FragmentAdressAdd.java
app/src/main/java/com/unipet7/mcommerce/fragments/FragmentAllProduct.java
app/src/main/java/com/unipet7/mcommerce/fragments/Home.java
app/src/main/java/com/unipet7/mcommerce/models/Addresses.java
app/src/main/java/com/unipet7/mcommerce/models/Product.java
app/src/main/java/com/unipet7/mcommerce/models/User.java
app/src/main/java/com/unipet7/mcommerce/utils/Constants.java
app/src/main/res/layout/layout_address_list.xml

Func: User's Addresses

---

app/src/main/java/com/unipet7/mcommerce/fragments/FragmentAddressEdit.java
app/src/main/res/layout/fragment_address.xml
app/src/main/res/layout/fragment_address_edit.xml
app/src/main/res/layout/fragment_adress_add.xml
app/src/main/res/layout/layout_address_list.xml

Update Func: User's Addresses

---

app/src/main/java/com/unipet7/mcommerce/activities/DetailProduct.java
app/src/main/java/com/unipet7/mcommerce/activities/MainActivity.java
app/src/main/java/com/unipet7/mcommerce/adapters/MainViewPager2Adapter.java
app/src/main/java/com/unipet7/mcommerce/firebase/FireStoreClass.java
app/src/main/java/com/unipet7/mcommerce/fragments/CartOverall.java
app/src/main/res/layout/fragment_cart_overall.xml

Update Cart Logic Ui

---

app/src/main/java/com/unipet7/mcommerce/activities/MainActivity.java
app/src/main/java/com/unipet7/mcommerce/activities/PaymentMethodDetails.java
app/src/main/java/com/unipet7/mcommerce/adapters/AddressAdapter.java
app/src/main/java/com/unipet7/mcommerce/adapters/DetailCheckoutHelper.java
app/src/main/java/com/unipet7/mcommerce/adapters/PaymentMethodListener.java
app/src/main/java/com/unipet7/mcommerce/fragments/FragmentAddress.java
app/src/main/java/com/unipet7/mcommerce/fragments/FragmentPaymentMethod.java
app/src/main/java/com/unipet7/mcommerce/utils/Constants.java
app/src/main/res/layout/layout_address_list.xml

Func: Change address in cart Details

Func: Change address in cart Details

---

app/src/main/java/com/unipet7/mcommerce/activities/SearchProductList.java
app/src/main/res/layout/fragment_home.xml

change banner into round corner

change banner into round corner

---

app/src/main/java/com/unipet7/mcommerce/activities/DetailProduct.java
app/src/main/java/com/unipet7/mcommerce/activities/VoucherActivity.java
app/src/main/java/com/unipet7/mcommerce/fragments/CartList.java
app/src/main/java/com/unipet7/mcommerce/models/Voucher.java
app/src/main/java/com/unipet7/mcommerce/utils/Constants.java

Func: add Fav from product detail and refactor Voucher Activity

Func: add Fav from product detail and refactor Voucher Activity

---

app/src/main/java/com/unipet7/mcommerce/activities/DetailProduct.java

Func: add and remove fav in product detail

Func: add and remove fav in product detail

---

app/src/main/java/com/unipet7/mcommerce/activities/VoucherActivity.java
app/src/main/java/com/unipet7/mcommerce/fragments/CartList.java

Revert cartList file
